### ISSUE TITLE
Unable to reset cache from webhooks

### ISSUE THREAD

**Issue by maqen** [contentful/contentful_rails#12]
Webhooks for clearing cache is now throwing an error how can I solve this?

``` ruby
NoMethodError (undefined method `clear_cache_for' for nil:NilClass):
vendor/bundle/ruby/2.2.0/gems/contentful_rails-0.2.1/lib/contentful_rails/engine.rb:37:in `block (2 levels) in <class:Engine>'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/fanout.rb:127:in `call'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/fanout.rb:127:in `finish'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/fanout.rb:46:in `block in finish'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/fanout.rb:46:in `each'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/fanout.rb:46:in `finish'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:36:in `finish'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:25:in `instrument'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.2.0/gems/contentful_rails-0.2.1/app/controllers/contentful_rails/webhooks_controller.rb:23:in `create'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

**Comment by dlitvakb** [comment]
This issue has been solved for over a year, closing.
