### ISSUE TITLE
undefined method `management_token=' for #<ContentfulRails::Configuration:0x007fc86564b510> (NoMethodError)

### ISSUE THREAD

**Issue by robcole** [contentful/contentful_rails#17]
Rails version: 5.0.0
Gem version: contentful_rails (0.2.3)

Steps to duplicate:

Add simple initializer. Attempt to launch server.

```
# config/initializers/contentful.rb
ContentfulRails.configure do |config|
  config.authenticate_webhooks = true # false here would allow the webhooks to process without basic auth
  config.webhooks_username = "a basic auth username"
  config.webhooks_password = "a basic auth password"
  config.access_token = "your access token"
  config.preview_access_token = "your preview access token"
  config.management_token = "your management access token"
  config.space = "your space ID"
  config.options = "hash of options"
end

rails c =>  /app/user/config/initializers/contentful.rb:7:in `block in <top (required)>': undefined method `management_token=' for #<ContentfulRails::Configuration:0x007fc86564b510> (NoMethodError)
        from /bundle/gems/contentful_rails-0.2.3/lib/contentful_rails.rb:19:in `configure'
```

**Comment by dlitvakb** [comment]
Hey @robcole,

The `management_token` is not yet released - we're testing it as a beta, it's only in master. If you want to use it, please use the git branch instead of the gem.

Hope that helps,

Cheers
